In a sample of size $(n)$ the expected value of the $(r)$ th largest order statistic is given by
$$
E(r, n) = \frac{n!}{(r - 1)!(n - r)!} \int_{-\infty}^{\infty} x(1 - \Phi(x))^{r-1}(\Phi(x))^{n-r}\phi(x) \, dx,
$$
where 
$$
\phi(x) = \frac{1}{\sqrt{2\pi}}\exp\left(-\frac{1}{2}x^2\right)
$$
and
$$
\Phi(x) = \int_{-\infty}^{x} \phi(z) \, dz.
$$

Royston, J. P. (1982). Algorithm AS 177: Expected normal order statistics (exact and approximate). Journal of the royal statistical society. Series C (Applied statistics), 31(2), 161-165.

In [ ]:
from scipy.integrate import quad
from scipy.special import binom
from scipy.stats import norm
import numpy as np

In [3]:
inf, phi, Phi = float('inf'), norm.pdf, norm.cdf

def E(r, n):
    def f(x):   
        F = Phi(x)
        return x*(1-F)**(r-1)*F**(n-r)*phi(x)
    return r*binom(n, r)*quad(f, -inf, inf)[0]

In [73]:
m=np.array([E(i,10) for i in range(1,11)])
m=m[::-1]
m=m.reshape((10,1))
m

array([[-1.53875273],
       [-1.00135704],
       [-0.65605911],
       [-0.3757647 ],
       [-0.12266775],
       [ 0.12266775],
       [ 0.3757647 ],
       [ 0.65605911],
       [ 1.00135704],
       [ 1.53875273]])

**Covariance Matrix, V**

$V_{i,j}=\mathbb{E}[(Z_{(i)}-m_i)(Z_{(j)}-m_j)]$

In [46]:
np.random.seed(2609)
matrix=np.random.normal(0,1,(1000000,10))
matrix=np.sort(matrix,axis=1)
matrix

array([[ 2.35676065,  1.03004855, -2.02258982, ...,  1.30640262,
        -0.81895459,  1.45529678],
       [-1.14898889,  0.65898349, -0.55883736, ..., -2.3236977 ,
        -0.26551878,  0.04511493],
       [-0.79857022,  2.40098544,  0.12351406, ...,  0.56901273,
        -1.38408064, -0.09072097],
       ...,
       [-1.44008624, -1.24841506, -0.45013202, ..., -0.04813313,
         0.68951906, -0.5623948 ],
       [ 0.76879009,  1.81966713, -0.81335319, ..., -0.13159266,
        -0.45002537, -0.78517371],
       [-0.93704861, -1.38512201, -0.37541713, ..., -0.01687263,
         1.35122507,  0.66852956]])

In [48]:
cov_matrix = np.cov(matrix, rowvar=False)
cov_matrix

array([[0.34452649, 0.17148268, 0.11636244, 0.08797247, 0.07062324,
        0.05835302, 0.04886994, 0.04097862, 0.03395854, 0.02680342],
       [0.17148268, 0.21470557, 0.14675017, 0.11149474, 0.08966637,
        0.07403015, 0.06211368, 0.05214047, 0.04330846, 0.03371779],
       [0.11636244, 0.14675017, 0.17506564, 0.13352363, 0.10760177,
        0.08901699, 0.0748482 , 0.06288995, 0.05228875, 0.0408636 ],
       [0.08797247, 0.11149474, 0.13352363, 0.15766073, 0.12738732,
        0.10559131, 0.08881747, 0.07477236, 0.06209446, 0.04865725],
       [0.07062324, 0.08966637, 0.10760177, 0.12738732, 0.15119823,
        0.12574584, 0.10604351, 0.08933701, 0.07425264, 0.05850678],
       [0.05835302, 0.07403015, 0.08901699, 0.10559131, 0.12574584,
        0.15124169, 0.12780721, 0.10788928, 0.0899069 , 0.07094881],
       [0.04886994, 0.06211368, 0.0748482 , 0.08881747, 0.10604351,
        0.12780721, 0.15819085, 0.13387733, 0.1119317 , 0.08859096],
       [0.04097862, 0.05214047, 0.0628899

In [65]:
np.linalg.inv(cov_matrix)

array([[ 4.81808666e+00, -3.88517720e+00,  2.60816945e-02,
         2.72735648e-02,  1.64563027e-02, -1.23575319e-02,
         5.60305136e-03, -2.56701855e-04,  1.10828213e-02,
        -8.68814788e-03],
       [-3.88517720e+00,  1.40396791e+01, -9.22786175e+00,
         2.96969274e-02, -9.64267860e-04,  1.99901297e-02,
         1.70239237e-02,  4.21920791e-03, -9.24344802e-03,
         1.34048524e-02],
       [ 2.60816945e-02, -9.22786175e+00,  2.39059059e+01,
        -1.37833351e+01,  3.46778680e-02,  4.40784163e-02,
        -3.69712747e-02,  3.78761892e-02, -1.78829289e-02,
         2.90378090e-03],
       [ 2.72735648e-02,  2.96969274e-02, -1.37833351e+01,
         3.15701081e+01, -1.69019253e+01,  2.87122744e-02,
         9.28360849e-02, -2.79978173e-02,  5.39205577e-03,
         1.84237412e-02],
       [ 1.64563027e-02, -9.64267860e-04,  3.46778680e-02,
        -1.69019253e+01,  3.57505141e+01, -1.79636665e+01,
        -2.45943871e-02,  1.86004472e-02,  4.63184028e-02,
        -1.

In [77]:
m.T @ (np.linalg.inv(cov_matrix)) @ (np.linalg.inv(cov_matrix)) @ m

array([[38.13310932]])

In [78]:
m.T @ (np.linalg.inv(cov_matrix))

array([[-3.55462259, -2.01443463, -1.30547474, -0.76484563, -0.25579514,
         0.23408777,  0.7482864 ,  1.33248291,  2.01907983,  3.55221237]])

In [61]:
np.mean(matrix,axis=0)

array([-1.53894925, -1.001301  , -0.65612385, -0.3755983 , -0.12238104,
        0.12301852,  0.37589477,  0.65623326,  1.00140687,  1.53761375])

In [62]:
m=np.array([E(i,10) for i in range(1,11)])
m=m[::-1]
m

array([-1.53875273, -1.00135704, -0.65605911, -0.3757647 , -0.12266775,
        0.12266775,  0.3757647 ,  0.65605911,  1.00135704,  1.53875273])

In [66]:
import numpy as np

# Creating an example square matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculating the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:\n", matrix)
print("Inverse Matrix:\n", inverse_matrix)


Original Matrix:
 [[1 2]
 [3 4]]
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [68]:
import numpy as np

# Creating two example matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Method 2: Using @ operator
product2 = matrix1 @ matrix2

print("Product using @ operator:\n", product2)


Product using @ operator:
 [[19 22]
 [43 50]]
